### ISSUE TITLE
WizNote.ahk

### ISSUE THREAD

**Issue by zhuatw** [goreliu/vimdesktop#1]
您好：
    先简要的介绍下：
    本人是非 IT 人员，我到是有兴趣做这个脚本的使用测试，
    先咨询第一个问题：
    为知笔记里的键绑定是好像不能用！
    用鼠标点击（个人笔记中的文件夹后，j 键能用一次，再次 t 键并不能重复选择到
    "定位到左侧目录" )

```
第二个问题：
```

   有没有在那里设置 vimdesktop 中的全局键对某个类型的窗口可以失效，
    如我现在的用的 spacemacs 窗口，多说一句，我主要是用 emacs 中的 org-mode
    来写文档的，别的都不会，在网上现学的。

**Comment by zhuatw** [comment]
vim.comment("<WizNote_List>", "定位到左侧目录")

**Comment by zhuatw** [comment]
vim.comment("<WizNote_List>", "定位到左侧目录")

**Comment by goreliu** [comment]
@zhuatw 

因为有时按完j后，焦点会跳到右侧正文部分，按j就没用了。可以用J，它会先把焦点重新放到左侧目录。因为之前我想让在右侧的正文编辑时也可以用jk来移动光标，所以J和j是不同的。

如果这个窗口只属于一个软件的，可以屏蔽这个软件，在配置文件的

```
[exclude]
vim
```

里添加，用Au3_Spy.exe获取到对应窗口的ahk_class。

如果不想屏蔽整个软件，或者这类窗口在很多软件里边都有，现在没有方便的办法屏蔽，只能在每个插件里自己加上屏蔽窗口的classnn。但因为VimDesktop只对有对应插件的软件使用快捷键，你是指General模式的情况吗？那只在General插件里加上屏蔽窗口的classnn就可以了。

**Comment by zhuatw** [comment]
[exclude] 处当时没细看，多谢提醒 ！
另外，在网页上看到好像为知是 Qt 编写的，使用时鼠标点击笔记的文件列表后，焦点先高亮几秒，接着焦点就自动转移了；我现在是看 AppsKey 基上用的不多，就直按把代码加到 vimd.ahk 最后面，再把[plugins] 处 WizNote=0 ，使用时是先 AppsKey & f 定位到为知笔记的文件夹上：

``` ahk
;wzi folder Control
AppsKey & f::
IfWinNotExist, ahk_class WizNoteMainFrame
  Send ^!m
WinActivate, ahk_class WizNoteMainFrame
ControlFocus, CWizMultiSelectTreeCtrl1, ahk_class WizNoteMainFrame
Return

AppsKey & k::
Send {Up}
Return

AppsKey & j::
Send {Down}
Return

AppsKey & h::
Send {Left}
Return

AppsKey & l::
send {Right}
Return

AppsKey & n::
Send {F8}
Return

AppsKey & p::
Send {F7}
Return

AppsKey & RAlt::
Send {AppSkey}
Return
```

**Comment by zhuatw** [comment]
补充下：上述的 ahk 单独一个脚本才能用，因为放到 vimd.ahk 中最后面，刚启动时好像能用，当在为知中用过搜索还是什么其它的操作后，就失效了，可能与 vimd.ahk 有冲突，具体原因？
我也不知道！

**Comment by goreliu** [comment]
@zhuatw
应该没有什么冲突，原因得具体调了，最好还是单独运行吧。

**Comment by goreliu** [comment]
@zhuatw 
在新版本我增加了一个功能，你可以把这段代码放到vimd.ini所在目录下的custom.ahk，然后vimd就会自动include它，我试了下，是没有问题的。

**Comment by zhuatw** [comment]
TTOTAL_CMD 中的 " n"  " <TC_azHistory> "  "a-z 历史导航“，
现在是可以呼出此历史，但是再用 a-z 键不能跳到相应的选择？

**Comment by goreliu** [comment]
那按a-z是没反应还是退出历史，用的自带的vimd.exe吗？

**Comment by zhuatw** [comment]
我没用 vimd.exe ，我有装 AHK ，刚才也重下载了 AHK 的最新版，也是用的你的最新主分支，电脑也重启来试，结果还是没用。
具体表现为：
按 n 会出现历史 a-z ，再按相应的字母键就只退回到 TC 中，它并没转到相对应的历史文件目录中。

**Comment by goreliu** [comment]
无法复现，只能你直接调下代码了，看下什么地方出错了。
