### ISSUE TITLE
请问能否仅将Win+T设置为全局使用？

### ISSUE THREAD

**Issue by hongyuanjia** [goreliu/vimdesktop#10]
你好！
在使用中发现，在vimd.ini默认将Vim设置在了Exclude项中。这样在使用中就会出现如果打开了gVim便无法使用Win+T的默认快捷键来调出TC，而只能先切换到其他程序当中，再按该键来调出。
请问有没有什么方法可以仅将Win+T设置为不对gVim排除呢？
谢谢！

**Comment by goreliu** [comment]
把 Exclude 中的 Vim 去掉就可以了。
