### ISSUE TITLE
TC 升级到 beta 13后，mark 功能异常

### ISSUE THREAD

**Issue by Liuzhj** [goreliu/vimdesktop#11]
# 信息

OS: win10
TC: TC9 beta 13
vimd 2.14 
# 情况
- 按 ' (单引号)，可弹出mark list ,选择其中某个mark list后，按回车，目录不跳转，再按下 enter 键，目录才会发生跳转。
- 希望可以得到帮助 。谢谢

**Comment by goreliu** [comment]
在 `plugins/TotalCommander/TotalCommander.ahk` 的 826 行加个 `Sleep, 50`，暂时可以解决，如果不行可以再调长一些时间。具体原因不大清楚，我可能等 TC 9 发布后再统计检查下兼容性问题。

**Comment by Liuzhj** [comment]
@goreliu  谢谢您的回复，会一直支持下去！再次感谢。

**Comment by goreliu** [comment]
我在 9.0a rc2 试貌似正常了。

**Comment by Liuzhj** [comment]
@goreliu 

好的，我用RC2 再测试下。
但现在我遇到一个问题，按下单引号打开mark后，出现一个大写的ERROR，之前是没有的，是怎么回事呢？

另外，标记一个路径，删除的时候不是可以直接编辑TCMark.ini吗？为什么删除了对应的标记，再次按单引号的窗口中还是会显示呢？

**Comment by Liuzhj** [comment]
@goreliu  

那个ERROR 没有了，我做了以下的操作，并且描述下我的理解：
1.  ms=xxx   这个是与下面具体的标记相匹配的，如果ms对应的字符串没有匹配到对应的路径，那么就会显示 ERROR。
2. 如果想要删除标记，不仅要删除TCMark.ini文件里对应的那一行，ms=后的字符串也要删掉。
3. 并且删除完成后，要重启vimd才会生效。


以上是我的理解，如果不对还望指正。

**Comment by goreliu** [comment]
只改ms=一行就可以
