### ISSUE TITLE
windows 10 重启电脑后vimd异常闪退

### ISSUE THREAD

**Issue by Liuzhj** [goreliu/vimdesktop#12]
不记得自己对操作系统做过什么修改，现在是每次重启后vimd都会闪退。不能正常运行。

不知道可以提供什么你可以拿来测试？

**Comment by goreliu** [comment]
不知道现在还有没有这个现象，另外可以试下把 vimd.exe 换成最新版本的 ahk。

**Comment by goreliu** [comment]
无后续反馈，关闭。
