### ISSUE TITLE
设置 {;} 为修饰键后，无法打出 {:} 这个符号

### ISSUE THREAD

**Issue by leeguoren** [goreliu/vimdesktop#14]
代码如下：
$SC27::Send {;}
SC27 & a::Send ^a

 linxinhong 版本下没问题

**Comment by goreliu** [comment]
我只运行这个脚本，不运行 vimd，就会打不出冒号。

**Comment by leeguoren** [comment]
我最后是 
+SC27::Send {: Down}{: Up}  
SC27::Send {; Down}{; Up}
来解决这个问题的，可能是 AutoHotkey 问题

**Comment by goreliu** [comment]
有可能。用分号当修饰键确实是个不错的方法。

**Comment by leeguoren** [comment]
其实更好的办法是参照  MAC 的 Karabiner，全局映射
开启 VI Mode 功能（按住 S 键后， HJKL 变成 左下上右键）
开启 Mouse Key 功能（按住 D 键后， HJKL 可以控制 鼠标左下上右）

只不过 AutoHotkey，无法设置 按住 S 键要达到 0.5秒 以上， HJKL 才能变成 左下上右键，（不设置按住     S 时长的话，会造成打字速度快的时候SH... 会误误触发）

**Comment by leeguoren** [comment]
所以只能用比较次的办法，将打字的时候不会连按的键，如 {;}、{Esc} 当修饰键 （当然 Caps Lock 和 Esc 两个按键以对调），当想用修饰键的时候 ，直接用 左手小拇指按住 Cap Lock 键 就是修饰键， 单按 Cap Lock 是 Esc 的效果， 而右手小拇指按住 {；} 是 Ctrl 修饰键，单按{；} 就是原来的效果

**Comment by leeguoren** [comment]
不知道博主，有没什么好办法可以 实现  按住 S 键要达到 0.5秒 以上， HJKL 才能变成 左下上右键，这种效果

**Comment by goreliu** [comment]
想到一个笨办法，设置一个计数器，每次按 S 键加 1，如果短时间计数器达到一定数值并且计数器最近更新过就映射按键，否则就清空计数器（下次按 S 键时）。

**Comment by goreliu** [comment]
我是用左 Alt 作为修饰键的，右 Alt 是正常的功能，基本不影响日常使用。
