### ISSUE TITLE
允许把CapsLock作为修饰键

### ISSUE THREAD

**Issue by thawk** [goreliu/vimdesktop#15]
由于CapsLock占用了很好的位置，其功能又能被Shift代替，因此如果能把CapsLock作为修饰键，就可以和60%键盘一样，用CapsLock+H/J/K/L作为方向键，并且增加很多方便的组合键。

**Comment by goreliu** [comment]
在注册表把它改成 Esc 或者 Ctrl 应该是更好的方法。作修饰键存在一些麻烦（比如 vimd 不支持多按键同时按的绑定，改起来比较麻烦），不考虑支持。

**Comment by thawk** [comment]
其实不是想把CapsLock和ESC或者Ctrl对调，而是想多出一组组合键，改注册表达不到这样的效果。看来只能用单独的ahk脚本实现了

**Comment by goreliu** [comment]
你可以参考下这个 https://github.com/Vonng/Configuration/blob/master/app/ahk/CapsLock.ahk

**Comment by aodiquan** [comment]
CapsLock我参考[http://www.cnblogs.com/Vonng/p/4294344.html](url)这个改造，按下CapsLock相当于是esc，在其他软件都是能识别是esc，但是vimDesktop下不行，无法进入normal模式，但是按下esc是可以进入normal模式的，怀疑vimDesktop和这种CapsLock的改造都是用autohotkey写的情况下，vimDesktop识别出来的依然是CapsLock而不是esc

**Comment by ifnk** [comment]
作者 你好，我有一个想法 是 将 capslock 映射成 f20键， 在通过 f20 +hjkl 之类 的 形成 组合 键， 这样 不会出问题…… 我参考了 https://www.cnblogs.com/xrvu/p/9782148.html 这个文章 的，但是 不知道怎么集成到 vimd 里面 ……
