### ISSUE TITLE
使用<w-t>复制热键到当前窗口以后，没有屏蔽无效键

### ISSUE THREAD

**Issue by zhou1012** [goreliu/vimdesktop#16]
在normal模式下，未设置键仍然会输入字符，有时候造成模式判断的混乱

**Comment by goreliu** [comment]
`<w-t>` 只供临时使用，可以在配置文件里对特定软件进行定制按键，把按键映射到` <Pass> `是屏蔽按键。

**Comment by goreliu** [comment]
实际上通用模式是比较鸡肋的，各个软件能通用的功能基本只有方向键等少数按键，我自己是将通用的功能都映射到 alt + 按键了，这样不需要切换模式就能用，也不需要判断现在处于什么模式。
