### ISSUE TITLE
,标记功能不能用

### ISSUE THREAD

**Issue by brucmao** [goreliu/vimdesktop#17]
刚更新了，我将d改为常用文件夹，但是 , 标记功能不能用，是打开下方命令框，并且自动输入m
![TIM截图20171119213916.jpg](https://i.loli.net/2017/11/19/5a1189905c4a8.jpg)

**Comment by brucmao** [comment]
会了，原来是输入 , 后，再输入 p 就会标记这样，但是没有找到怎么删除这些标记
![snipaste20171119_223856.png](https://i.loli.net/2017/11/19/5a119788c6c30.png)

**Comment by brucmao** [comment]
找到了，在totalcmd目录下有个TCMark.ini，建议在vimd里面再增加个删除的快捷键吧

**Comment by goreliu** [comment]
用快捷键删除的话不大好操作，我是把打开 TCMark.ini 文件映射到某个快捷键上，然后直接编辑文件。
