### ISSUE TITLE
编译后无法运行

### ISSUE THREAD

**Issue by zhixing2017** [goreliu/vimdesktop#19]
使用ahk2exe编译后，运行时出错。如下：

![tim 20180306112330](https://user-images.githubusercontent.com/26316963/37012674-d44046f0-2130-11e8-9c79-315d0e58a99c.png)

**Comment by goreliu** [comment]
修复了，https://github.com/goreliu/vimdesktop/commit/9b43f43b0748d6f7000ef819d4d19c24788aaa27
但编译后还需要依赖一些文件，功能也可能有问题，不建议编译后使用。

**Comment by zhixing2017** [comment]
这样啊，因为我的电脑配置有点低，ahk直接运行的话经常没反应，exe的话会好点。

我试试吧，谢谢了。

**Comment by zhixing2017** [comment]
编译后，可以使用。还没有遇到问题，有问题再说吧。基本上也用不了多少功能。
