### ISSUE TITLE
关于vimd.ini

### ISSUE THREAD

**Issue by wideweide** [goreliu/vimdesktop#2]
下载体验了一下
- vimd.ini 默认不提供，忽略该文件，由程序运行时自动生成，毕竟每个人的配置都不一样。这样每次直接同步代码就可以使用最新的版本了
- 修改vimd.ini后会自动重启吗？另外用菜单重启的时候，几乎没有成功过，总是提示：Could not close the previous instance of this script...

**Comment by goreliu** [comment]
@wideweide 

第一点可以考虑，后续版本我会改成这样。
修改vimd.ini不会自动重启，我感觉还是手动重启比较好。我一般用快捷键重启，菜单也用过，没遇到过“Could not close the previous instance of this script...”这个问题，每次都是吗？

**Comment by goreliu** [comment]
@wideweide 

现在主干代码改成这样了，删除了vimd.ini，运行时若无此文件，自动复制vimd.ini.help.txt为此文件。

**Comment by wideweide** [comment]
@goreliu 我这边每次都重现Could not close the previous instance of this script...
我是把autohotkey.exe改成vimd.exe拖进去这么用的，不知道跟这个有没有关系

Version language : 英语(美国)
      FileDescription   : AutoHotkey Unicode 32-bit
      FileVersion   : 1.1.23.01
      InternalName  : AutoHotkey
      LegalCopyright    : Copyright (C) 2003-2013
      OriginalFilename  : AutoHotkey.exe
      ProductName   : AutoHotkey
      ProductVersion    : 1.1.23.01

**Comment by goreliu** [comment]
@wideweide 
我用的也是这个版本，这样用没复现，不知道什么原因。
好像没有其他人反馈这个现象，不知道是否是你的环境有些问题。

**Comment by wideweide** [comment]
- 所有参数如果不设置，可以有个默认值最好...
- plugins.ahk也加到.gitignore中，另外可以把整个忽略文件只在根路径保存一份，看上去更清爽一点

另外同步最新代码后，可以正常重启无报错了
