### ISSUE TITLE
运行 RunZ.ahk 出错，RunZ.exe 正常

### ISSUE THREAD

**Issue by Skylarzz** [goreliu/vimdesktop#21]
请教
![default](https://user-images.githubusercontent.com/14090545/37386641-4c010fb2-2794-11e8-8c79-c08de27814a9.png)

**Comment by goreliu** [comment]
用的自带配置文件，还是自己之前的？

自带配置应该不会出错，如果是自己之前的，看下里边有没有和 RunZ 有关的配置，删掉再试试。

**Comment by Skylarzz** [comment]
谢谢，不是配置文件的问题，我发觉问题比较复杂

当以 `vimd.ahk` 运行，而非 `vimd.exe` 时， `<w-h>=run|..\RunZ\RunZ.ahk
` 的行为会很奇怪．
它不是简单地到 `vimd.ahk` 的上一级路径中查找 `RunZ\RunZ.ahk`，而是到「正在运行的所有进程的路径」中找查找`RunZ\RunZ.ahk`
最后执行的结果，可能会毫无反应，可能会去执行 `D:\autohotkey\RunZ.ahk` 之类的然后报错找不到文件，也可能会执行正确的结果

`vimd.exe` 没有问题
现在把配置改成了 `<w-h>=run|%A_ScriptDir%\..\RunZ\RunZ.ahk`，可以正确运行
