### ISSUE TITLE
Vm和Q键的连续按键触发bug

### ISSUE THREAD

**Issue by ghost** [goreliu/vimdesktop#22]
Vm：显示/隐藏菜单栏
Q : 启用、禁用菜单栏
按一次没问题，但是在重复操作会关闭当前TC并再开启好几个TC(没有选择"每次仅允许一个TC运行"，如果选择只会再次开启一个TC)
目测toggle菜单栏相关的命令有BUG
(TC版本 : 9.12  WIN7 sp1 x64)

**Comment by goreliu** [comment]
重新显示菜单必须重启 TC，因为实现上就是修改 TC 的配置文件，然后重启 TC，这个没办法。

**Comment by ghost** [comment]
好的，谢谢这么快速的回复 :D

**Comment by Liuzhj** [comment]
@goreliu 那为什么打开多次TC呢？ 我理解需要修改TC的配置文件，但不应打开多次啊，应该只打开一次才对。
实际上按下Q以后，会打开4个TC窗口。
