### ISSUE TITLE
建议增加快捷键在平行目录跳转

### ISSUE THREAD

**Issue by brucmao** [goreliu/vimdesktop#23]
![TIM截图20180612123851.png](https://i.loli.net/2018/06/12/5b1f4e9807d4f.png)
如我打开ZK188这个文件夹后，想一键跳转到ZK187或者ZK189目录下。
我知道有TC插件，tcimg 可以实现，对应参数 parll=0 打开下一个同级目录，parll=1 打开上一个同级目录。
感觉用要是用vimd的单键模式更方便。

**Comment by goreliu** [comment]
添加了（ https://github.com/goreliu/vimdesktop/commit/f7c3295775641c04c9dfdf60281e3be94ef8a317 ）。

<TC_PreviousParallelDir> 向上
<TC_NextParallelDir> 向下

**Comment by brucmao** [comment]
大佬又回来了，又要添加啥新功能

**Comment by goreliu** [comment]
刚才的版本问题比较多，改了一版。不会打开文件了，在分区根目录也可以跳转到上/下一个分区了。

https://github.com/goreliu/vimdesktop/commit/77696390dfe668e275a069a3a91f39c73081f5eb

但不能绑定到 `ctrl + ...` ，可以 `shift + ...`，而且如果按住了还是有可能出错。

暂时不添加新功能了。
