### ISSUE TITLE
想在 vimd里面 加入 caps修饰键，；分号 修饰键 应该怎么加呢

### ISSUE THREAD

**Issue by ifnk** [goreliu/vimdesktop#26]
;Capslock用作修饰键
#inputlevel,2
$CapsLock::F20
#inputlevel,1
;单按Capslock 是 esc的功能 
F20::Escape
;Capslock 实现上下左右,删除,回车等
F20 & H::
send,{left}
#inputlevel,0
将大写 映射成 f20键，通过 f20 +hjkl 实现上下左右 ，我将这个ahk 文件  放到 了 custom.ahk 里面 加载 ，但是 重启 vimd 没有反应…… 不知道怎么改……

**Comment by ifnk** [comment]
我 在custom.ahk 文件 里面 写了
;分号相关的快捷键
;=======================================================
;+sc027::Send {: Down}{: Up}
;sc027::Send {; Down}{; Up}
sc027:: `;
sc027 & z::send {'}
sc027 & f::send {\}
sc027 & c::send {"}
这些代码 ，意思 是 按分号键发送 分号 ，然后 分号键还能 当 修饰键，我在切到 tc里面 ，按分号键 ，tc的收藏夹就 再也调不出来 了…… 而是在搜索栏里 输入 了一个分号 进行 搜索了， 我想要 按分号 调出收藏夹，我应该怎么更改 我的代码 呢？

**Comment by ifnk** [comment]
能不能直接 在 vimd 里面 定义  分号 为修饰键呢？

**Comment by goreliu** [comment]
不支持。

**Comment by ifnk** [comment]
vimd 能不能在 原有的 insert  normal 模式 下 再 新建 一 个 search 搜索 模式 呢 ？ 因为经常 在 normal 模式 下 搜索 ，导致触发normal 模式的动作  一些字母 按不出来 ……

**Comment by goreliu** [comment]
不再处理 Issues。
