### ISSUE TITLE
关于m标签功能的建议

### ISSUE THREAD

**Issue by wideweide** [goreliu/vimdesktop#3]
可持久保存标签比之临时保存有了很大提升，另建议实现：
- 支持多键标签，一键较少，且不太容易记忆
- 可移除标签

**Comment by goreliu** [comment]
多键标签，我想了下感觉这种场景用d书签更合适一些，d书签可以放二级菜单，功能也更灵活一些。m标签实现上是根据单个字母定位的，配置文件也是如此，改起来比较麻烦。
移除标签现在可以通过编辑配置文件来，可以在d书签里增加一个编辑`TC目录\TCMark.ini`的命令（我设置为d;），然后按`d;`可以直接打开`TCMark.ini`，删除或调整菜单顺序时只需要修改`ms`中的字母，这样也更灵活些：

```
[mark]
ms=cdeipmlhqngsjzo;wt
c=&c >> c:\
d=&d >> d:\
e=&e >> e:\
i=&i >> c:\mine
p=&p >> c:\mine\app
m=&m >> c:\mine\music
l=&l >> c:\mine\app\0link
h=&h >> c:\mine\app\VimDesktop
q=&q >> \\回收站
n=&n >> \\网络
g=&g >> c:\Users\goreliu\AppData\Roaming\Microsoft\Windows\Start Menu\Programs
s=&s >> \\\Secure FTP Connections
j=&j >> e:\tmp
z=&z >> c:\mine\app\totalcmd
o=&o >> c:\mine\photo
b=&b >> c:\mine\app\VimDesktop
+=&; >> c:\Users\goreliu\Downloads
w=&w >> e:\store
t=&t >> e:\tmp

```

![](https://cloud.githubusercontent.com/assets/169704/13564739/c831bdaa-e486-11e5-920e-911520c2b439.png)

在界面删除，我没想到比较方便的方式。

m标签和d书签功能上是有重复的。d书签可以添加目录、文件、命令等，但添加比较麻烦，另外可能不够用。所以我想用m标签分担其中的一部分目录，这样d书签可以添加更多文件、命令等。两个结合起来用也许会好些。

**Comment by wideweide** [comment]
m标签和d书签是有重复的，且用起来都不尽如人意。理想的功能应该是这样的：

```
m***<CR>，支持任意多键，可记录关键字
'***,或o***，用来打开关键字对应的命令，其中'或o为导航前缀，可由用户定义

在vimd.ini中增加类似下属配置
oc=tcrun|cd c:\[=normal]
ofx=tcrun|cd c:\firefox\[=normal]

这要求快捷键对应的命令可带参数
```

**Comment by goreliu** [comment]
增加了一个`dir`类型命令，可以这样：

```
oc=dir|c:\
ofx=dir|c:\firefox\
```

**Comment by wideweide** [comment]
除了通过 m***<CR>，支持任意多键，可记录关键字

还有个问题就是这样子生成的快捷键，显示的快捷键声明不友好
![2016-03-15_141528](https://cloud.githubusercontent.com/assets/731627/13769175/75b03bfa-eab8-11e5-8782-4105ffcf4cbb.png)

似乎不支持中文文件夹 oqq=dir|S:\测试\

ｐｓ：ｃｄ感觉比ｄｉｒ更好

**Comment by goreliu** [comment]
快捷键显示这个是已知问题，已经改了。
中文文件夹是编码的问题，已经改了。
因为要向后兼容，就不改成cd了。

**Comment by wideweide** [comment]
用上了，非常感谢．

ｍ用来记录这个准备实现不？还是不好实现？

**Comment by goreliu** [comment]
m如果实现成多键用法和现在就不一样了，所以不能这样做。
如果添加一个新功能标签用来实现这个，看起来是没有太大问题的，以后有时间的话可能考虑下。
