### ISSUE TITLE
features of this project?

### ISSUE THREAD

**Issue by nnako** [goreliu/vimdesktop#31]
Hi,

unfortunately, I am not able to read any Japanese. So, I can not see which features are implemented within this project. As I am very much interested in providing / developing a specific form of keyboard mapping across the Windows environment, I was wondering if you could help me creating a list of fulfilled features, so that I can see if this project would be useful for my purposes:

**show current mode status**
show which mode is currently active. in vim, there are (among others) the NORMAL, INSERT, VISUAL and COMMAND LINE modes available. this might be shown e.g. by an icon within the task row.

**provide NORMAL mode**
this would be a mode in which navigation within the text as well as special transformation activities can be performed on the text.

**provide INSERT mode**
this would be the standard input mode which is active within all the "normal" editors all the time.

**command input**
like in vim the command line interface entered via ":" in NORMAL mode

**highlighting of text**
like in vim using "*" for highlighting the current word under the cursor and searching for the next occurrence

**auto-enable in known application**
provide automatic enable of specific keyboard mapping when a known (registered) application gets into window focus

**provide settings menu**
provide a way in which a user can comfortably change general or application-specific operation behavior

**application-specific mappings**
provide a set of keyboard mappings with respect to the specific application. so, in one application <K> means <UP> and in another it means <CTRL>+<W>.

**key -> activity mappings**
a single key press can be mapped to a sequence of specific key presses or other activities

**functional sequence -> activity**
a sequence of key presses is mapped to an activity. the source sequence is evaluated while typed. the target activity is triggered when a functional match was detected. the triggered activity is parametrized by the source sequence. this could be used to implement "yiW" (yank inside word) c.f. vim's NORMAL mode.

**static sequence -> activity**
a sequence of key presses is mapped to another sequence of key presses or an activity. the target sequence / function is triggered when a specific trigger key is pressed (e.g. <RETURN> or <TAB>). this can be used for common abbreviations within standard texts.

Are there maybe other features which this project covers?

I hope to receive some helpful statements ;-)

Thanks
Nnako

**Comment by goreliu** [comment]
I'm sorry to say that I don't know how to reply to you, and I will no longer deal with Issues.
