### ISSUE TITLE
关于ESC之后全局禁用输入法

### ISSUE THREAD

**Issue by wideweide** [goreliu/vimdesktop#5]
开启中文输入法状态下按下esc进入normal模式，部分应用的快捷键无法有效使用，建议按下esc进入normal模式时全局禁用中文输入法

**Comment by goreliu** [comment]
不同输入法的禁用方式是不一样的，快捷键也和用户的配置有关，我想不到统一的方法。

**Comment by wideweide** [comment]
参考代码

~esc::

Send, {ESC}

; 下方代码可只保留一个
SwitchIME(0x04090409) ; 英语(美国) 美式键盘
SwitchIME(0x08040804) ; 中文(中国) 简体中文-美式键盘
return

SwitchIME(dwLayout){
    HKL:=DllCall("LoadKeyboardLayout", Str, dwLayout, UInt, 1)
    ControlGetFocus,ctl,A
    SendMessage,0x50,0,HKL,%ctl%,A
}

**Comment by goreliu** [comment]
TC的加上了。
