### ISSUE TITLE
请问下如何把Caps映射成Esc?

### ISSUE THREAD

**Issue by aristotll** [goreliu/vimdesktop#7]
我以前用一个AHK小脚本映射的.

现在的vimdesktop里识别不了这个脚本做的映射了:估计都是AHK的缘故.

谢谢.

**Comment by goreliu** [comment]
用 ahk 映射有延迟，建议直接改注册表。

**Comment by aristotll** [comment]
在问个问题,不想另外开issue了

setWin 如何让class 可以正则匹配啊 

我想做一个插件 但是我的软件的类是会变的.虽然开头是一样的..

谢谢.

**Comment by goreliu** [comment]
class 不能正则匹配，这种情况可以用 exe。

**Comment by aristotll** [comment]
我直接写了exe的名字,但是desktop捕捉不到.试了下绝对路径貌似也不行?

谢谢

**Comment by goreliu** [comment]
不用绝对路径，写完整的程序名。

**Comment by aristotll** [comment]
成功了,原来类名必须加入占位的"",而不能空着...
谢谢

**Comment by aristotll** [comment]
再问个问题,thanks

如何忽略其他键:现在有个问题时在**普通模式**时我输入未绑定键照样有反应,如何让他忽略未绑定的键呢

**Comment by goreliu** [comment]
忽略未绑定的键，可以在配置文件里：

```
xx=<Pass>
```
