### ISSUE TITLE
请问能否实现Win+E打开TC时自动最大化呢？

### ISSUE THREAD

**Issue by hongyuanjia** [goreliu/vimdesktop#8]
最近一段时间一直在使用Vim，今天刚刚看到了VimDesktop，很好奇，便下载下来使用了。很方便，在此感谢开发者！

我想请问一下能否在按了Win+E弹出TC时使之全屏？另外，能否在开机运行VimDesktop时不再出现正在映射快捷键的窗口？

谢谢

**Comment by goreliu** [comment]
按了 Win + E 弹出 TC 时使之全屏的话，比较麻烦，或者改代码中的 `<TC_ToggleTC>`，加个 GoSub `<cm_Maximize>`，或者加个新标签依次调用 `<TC_ToggleTC>` 和 `<cm_Maximize>`。或者用 wshkey 依次调用 `<TC_ToggleTC>` 和 `<cm_Maximize>` 的热键也行。

**Comment by goreliu** [comment]
我在开机运行时没有出现正在映射快捷键的窗口，不清楚。
