### ISSUE TITLE
请问能否实现在TC应用快速搜索完成时应用j和k对结果进行选择

### ISSUE THREAD

**Issue by hongyuanjia** [goreliu/vimdesktop#9]
你好！
我在使用VimDesktop时发现，按“/“进行Quick Search后，无法使用j和k对结果进行选择，而只能使用方向键进行选择。
不知有没有什么设置选项可以解决这个问题？
谢谢！

**Comment by goreliu** [comment]
这个没办法，在搜索框里jk都是输入内容，esc 关掉搜索框就可以了。
